[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_SUPABASE_URL = "https://rxadlcvelitixlhptulb.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YWRsY3ZlbGl0aXhsaHB0dWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMzQ0NzMsImV4cCI6MjA1MTkxMDQ3M30.Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs"

[context.deploy-preview.environment]
  VITE_SUPABASE_URL = "https://rxadlcvelitixlhptulb.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ4YWRsY3ZlbGl0aXhsaHB0dWxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYzMzQ0NzMsImV4cCI6MjA1MTkxMDQ3M30.Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs_Qs6Qs"